:PROPERTIES:
:ID:       C64157A9-61B9-4D4C-B263-1A5A821EC0E0
:mtime:    20240323202627 20240323171124
:ctime:    20240321170322
:END:
#+title: 株式投資

* 基本情報

+ 邦題 :: 株式投資 -- 長期投資で成功するための完全ガイド
+ 原題 :: Stocks for the Long Run -- The Defencive Guide to to Finacial Market Returns and Long-Term Investment Strategies
+ 著者 :: ジェレミー・シーゲル
+ 訳者 :: 石川 由美子、鍋井 里依、宮川 修子
+ 監訳 :: 林 康史、藤野 隆太 

* 読書記録

** 読書時期

+ 開始 :: <2024-03-21 木>
+ 読了 ::  

** メモ

*** 第1部 株式投資の歴史的評価

**** 第1章 1802年以降の株式、債券の投資利回り

***** 結論：長期投資のための株式

株式の利回りは以下に左右される。

+ 資本の質と量
+ 生産性
+ リスクとリターンの関係

株価を高める要因は次の通り。

+ 優れた経営
+ 財産権を保証する安定した政治体制
+ 競争のもとで消費者によりよい商品を提供できる能力

***** 補足2：算術平均利回りと幾何平均利回り

算術平均利回り \(r_A\) は、毎年の投資利回りの平均を表す。

\[
r_A = \frac{(r_1 + r_2 + \cdots + r_n)}{n}
\]

幾何平均利回り \(r_G\) は、複利の投資利回りを表す。

\[
r_G = \{(1 + r_1) (1 + r_2) \cdots (1 + r_n)\}^{\frac{1}{n}} - 1
\]

ある投資で複利利回り \(r_G\) が得られるとき、資産は \(n\) 年で \((1 + r_G) n\) 倍に増加する。
幾何平均利回りと算術利回りの関係は次の式で表される。

\[
r_G = r_A - \frac{1}{2} \sigma^2
\]

ここで \(\sigma^2\) は年率利回りの分散を表す。

**** 第2章 リスク、リターン、資産分配


***** 株価のピークで投資を始めた場合の利回り

株価がピークにあるときに投資を始めたとしても、株式の利回りがほかの金融資産の利回りを上回る。

+ 保有期間30年 :: 長期債の4倍以上、短期国際の5倍以上
+ 保有期間20年 :: 債券の2倍
+ 保有期間10年 :: 若干上回る

投資家が株価の高値と安値を正確に言い当てられることができるならば、
バイ・アンド・ホールド戦略より大きな利回りを得られる。
株価の高値で売り抜けることができたとしても、それだけで他人を上回る利回りを手にすることができるとは限らない。
マーケットが高値で沸いているときに売るのは困難だが、
株価が安値にあり悲観論がはびこっているときに底値で買うのは、さらに難しい。
最高値で売却することは、株式を長期保有する投資家に打ち勝つことを保証するものではない。

***** 標準的なリスクの測定方法

保有期間が 15 ~ 20 年の場合、株式の投資リスクは長・短期債よりも小さくなる。
株式投資のリスクは長・短期債のリスクの4分の3以下に下がる。
保有期間が長くなるにつれ、株式の平均利回りの標準偏差は債券に比べて約2倍の速さで低下する。

***** 効率的フロンティア

***** 望ましい資産配分

**** 第5章 株式と債券の利回りに与える税の影響

税引き後の実質トータルリターンの最大化は、投資戦略の本質。
